#!/usr/bin/env python3
from fosspay.database import db
from fosspay.objects import Invoice
from fosspay.config import _cfg
import sys

if len(sys.argv) != 3:
    print("Usage: {} <amount in cents> <comment>".format(sys.argv[0]))
    sys.exit(1)

amount = int(sys.argv[1])
comment = sys.argv[2]

invoice = Invoice()
invoice.amount = amount
invoice.comment = comment
db.add(invoice)
db.commit()

print("{}://{}/invoice/{}".format(_cfg('protocol'), _cfg('domain'), invoice.external_id))
